### ISSUE TITLE
Add utility to convert Au time quantity to chrono duration

### ISSUE THREAD

**Issue by chiphogg** [aurora-opensource/au#187]
We could call this `to_chrono()` or `as_chrono()`.

**Comment by jaskij** [comment]
As of Arm GNU Toolchain 13.2 (released Oct 30), it throws an error that `<chrono>` is not available in freestanding implementations. Take care so this does not break builds. (In fact, that has been the kick for me to finally try out Au).

**Comment by chiphogg** [comment]
Thanks for bringing this to my attention!  I don't have any personal experience with freestanding configurations.

It looks like `<chrono>` is already unconditionally included in all of our single-file releases, so I don't think this new feature could break any builds that aren't broken already.  That said --- are you telling me that the builds are _already_ broken for single-file Au in freestanding configurations?  If so, I don't think that's insurmountable.  We could probably make our `chrono` support toggleable as well when we build the single file.  Would that be a feature you would find useful?

**Comment by jaskij** [comment]
Sorry for not being clearer with my edit - I did some more reading (including comments in that issue), and it seems that newlib (and perhaps similar alternative libc implementations) is in a weird limbo, where formally it *should* be `-ffreestanding`, *but* practically it behaves like a hosted implementation. Removing that flag does allow `<chrono>` to work.

The issue is, I believe, with those *truly* freestanding codebases, which don't depend on much (if any) of the standard library, but it seems as those were never really supported, so there's that.

No, it's not a feature I'd find useful - I'm using newlib for the C standard library and GNU's C++ standard library on top of it, and changing my build flags fixes things.

**Comment by chiphogg** [comment]
OK, thanks for following up and clarifying.  If we ever get requests for "true freestanding", it'll be interesting to see if we can satisfy them!
