### ISSUE TITLE
Get QuantityMaker from unit label

### ISSUE THREAD

**Issue by tsjung75** [aurora-opensource/au#220]
Is there any way to get QuantityMaker from unit label?
Let's say that there is a "duration" quantity in the Json file like below.

"duration": { "value" = 500, "unit" = "ms" }

I want to use "duration.unit" for get QuantityMaker - au::milli(au::seconds) and use this to generate Quantity - au::Quantity<au::Milli<au::Seconds>, size_t> instance.

**Comment by chiphogg** [comment]
What an interesting question!  In general, I think there will be aspects of this that are possible, and aspects that just aren't.

First, to clarify the request: can we write the signature of the desired function?  What type would it return?  I assume it takes a JSON object such as the above as its input.  If there are multiple possible `Quantity` types, and they depend on the unit listed, what type should the function return?

I can see a couple possibilities here.

1. If you have support for it (either from C++17 or from a library), you could use a "variant" based approach.  You could make a list of supported units, and select which alternative it holds based on the `unit` value.
2. If you know that your values will always have the same dimension, and you know what it is, then you could convert them all to some "common" quantity type that has that same dimension.  For example, maybe you have a length that could be in miles, inches, millimeters, whatever... but you're going to store it in meters.

Do either of these sound like what you have in mind, or can you think of another possible strategy for the return type?

In any case, it won't be possible to support "all units" with such an interface, because we don't have any concept of "all of the units" in the library (and even if we did, end users could always add more).  Thus, I think any possible solution here will work based on some list of supported units, which you will select at the time that you write the program.

**Comment by tsjung75** [comment]
Thanks for your comments.

Yes, because of the strong type nature of the library, this feature cannot be implemented simply.
Even though I use std::variant, I have to specify the type when I get the value.
So I'll just use the unit (or unit string) for reference.

**Comment by chiphogg** [comment]
OK, thanks for responding.  I'm going to go ahead and close the issue, because I don't see there's any work to do on our end.  We recommend users write their own function as they see fit for this kind of use case.  (It's what we've done internally at Aurora on top of Au.)  If I've missed anything, please feel free to respond again!
