### ISSUE TITLE
Defining labels of compount units

### ISSUE THREAD

**Issue by StefanoD** [aurora-opensource/au#231]
Hi,
first, thank you, for your great library!

Because I am missing basic units like Watts, Joule and Newton, I have to define them myself. That's Ok, but my problem is, that I want also define a new label for these new compount units like `W` for `Watts`, `J` for `Joule` and so on.
Is this possible?

Thanks in advance.

**Comment by chiphogg** [comment]
Sure!  This is a quick one, so I can answer it briefly right away.

We have a guide for [how to create new units](https://aurora-opensource.github.io/au/main/howto/new-units/).  It explains not just how to add a label, but also all of the other components you might consider adding, and what each one does.

That said, all of those units are already defined in the library.  I'm guessing you have been starting out with the "[pre-built single file](https://aurora-opensource.github.io/au/main/install/#pre-built-single-file)" approach?  If so, it would probably be easier to make a [custom single file](https://aurora-opensource.github.io/au/main/install/#custom-single-file).  I'd estimate it would take about 10 minutes, one time, and it should be a drop-in replacement that would give you the units you want right away.

Let me know how it goes!

**Comment by StefanoD** [comment]
Thanks for your quick reply!
I want actually to integrate every unit. This is because we are a big company and we want to deliver a software platform framework which every project depends on. That is, we cannot know in advance which unit we can skip. Therefore, we want to integrate every unit.
It's true that I used the pre-built one. But why is it that minimalistic?
Is there an easy way to get every supported unit without passing every single unit into a script as argument?

Regarding creating labels: Am I correct, that I have to use the `strong type` way? Is it possible to use the `alias` way and still create a custom label?

**Comment by chiphogg** [comment]
Please pardon my delayed response!  It's been a busy couple of weeks.

We do provide a mechanism for "just include all the units!".  It can be found at the end of the [single file section](https://aurora-opensource.github.io/au/0.3.4/install/#pre-built-single-file), where you can just go download the files.  (Click the orange bar at the end of that section to expand.)  You can also use the `--all-units` option instead of the `--units` option with the `make-single-file` tool to generate these files locally.

The all-units approach will get you up and running more quickly, but it comes at a cost: namely, compile time.  Each individual unit is very fast to compile, but they do add up.  Forcing every user to depend on all of them could make the overall compile time cost significant enough to notice.  I think with the present release, it's probably not too bad.  But you should be aware that the set of units could grow without bound in future releases.

The alternative would be to, yes, list every unit that your project uses, and then just regenerate the single file whenever somebody needs a new one.  It's of course up to you to evaluate the tradeoffs.  You can always start with `--all-units` and then provide optimizations later if users complain about compile times.

By the way, the best approach of all would be a "full install" rather than a single file approach.  Unfortunately, that isn't ready for CMake yet, although there's progress (#215) and I hope we can get this across the finish line in the next couple of months.  The good news is that you should be able to migrate pretty seamlessly from the single-file approach to full install when that becomes available, and users can "opt in" to the full install approach at the individual file level, for the files where people care the most about compile times.

> Regarding creating labels: Am I correct, that I have to use the `strong type` way? Is it possible to use the `alias` way and still create a custom label?

Actually, you can define a custom label for an alias!  The key is to explicitly specialize the `UnitLabel` template for the unit type, and give it an appropriate `value` member that is a char array.  See [this godbolt example](https://godbolt.org/z/6Exrjnnh5).  Here's the relevant snippet (assumed to be in the top-level global namespace):

```cpp
namespace au {
template <>
struct UnitLabel<UnitQuotientT<Meters, Seconds>> {
    static constexpr const char value[] = "mps";
};
constexpr const char UnitLabel<UnitQuotientT<Meters, Seconds>>::value[];
}
```

Note that if you deleted this from the link, you'd get the auto-generated label of `m / s` instead of `mps`.

**Comment by chiphogg** [comment]
I'm closing this before our team meeting today because I think it's been addressed.  If there are any outstanding problems, please feel free to reopen or to file a new issue!
