### ISSUE TITLE
Overwriting labels

### ISSUE THREAD

**Issue by StefanoD** [aurora-opensource/au#241]
Hi,
sorry, if I missed this in the documentation, but I want to overwrite existing labels. I. e., I want `au::Celsius` to have the label `"°C"` instead of `"degC"`. 
As the labels are declared as `constexpr`, it is not obvious to me if an overwrite is possible.

Thanks in advance.

**Comment by chiphogg** [comment]
I had thought this would be possible, but it looks like it isn't in most cases.

The natural approach would be to make a new specialization of `UnitLabel<U>` for your unit `U`, and give it a `value` member.  However, this won't work for a built in unit like `Celsius` or `Meters`, because the generic definition of, say, `UnitLabel<Meters>`, will already have been used somewhere.  (Turns out it's in the definition of the `unit_label(Meters{})` function.)  On reflection, I think we're lucky that the compiler caught this problem, because specializing traits in this way would probably be pretty error prone at best, and perhaps downright dangerous.

----

Good news, though!  I think you can get everything you want by just using a _different_ Celsius unit that has the label you want.  It'll be equivalent to Au's `Celsius` in every way that matters.  It can even interoperate with it!  (Although `Celsius{} / au::Celsius{}` won't _cancel out_, which is counter-intuitive, it _will_ create a unit that is equivalent to "the unit one", and you'll get generally correct results.)

Following the [new units guide](https://aurora-opensource.github.io/au/0.3.4/howto/new-units/), something like this should work:

```cpp
struct Celsius : au::Celsius {
    static constexpr const char label[] = "°C";
};
constexpr auto celsius_qty = au::QuantityMaker<Celsius>{};
constexpr auto celsius_pt = au::QuantityPointMaker<Celsius>{};

// This next line goes in the `.cc` file.
//
// (Or, if using C++17, just make the above definition `inline`.)
constexpr const char Celsius::label[];
```

Indeed, it certainly [appears to work](https://godbolt.org/z/3xaMMsjPY).  This definitely seems like a safer and better approach all around.

**Comment by StefanoD** [comment]
Thank you, that worked! :-)
