### ISSUE TITLE
Specialized Quantity Makers

### ISSUE THREAD

**Issue by StefanoD** [aurora-opensource/au#242]
Hi,
we are basicly using `au::QuantityD` everywhere which works quite fine with the corresponding Quantity Maker with the exception that i. e. templates are very strict. That is, if you have a single `typename T` with several parameters of the type `T`, it makes suddenly a difference if you pass i. e., `au::meters(1)` or `au::meters(1.0)`. That is, the former creates an compile error and the latter works.
I want to avoid this, such that my collegues (not all are actually software engineers, some are physicians, some biologists, some junior developers etc.) are not overwhelmed with strange template compiler errors.

Is there an easy way to make Quantity Makers which converts the input into a `double`?

Thanks in advance!

PS: Sorry, for the many question tickets. 🙁

**Comment by chiphogg** [comment]
No worries about the tickets. :sunglasses:  I'm glad it's useful for you!

I'm guessing this is for cases where the compiler will fail to deduce `T` unless it deduces `T` to be the same type for every individual parameter?

If the code would work in either case (as is often true), you could consider making separate template parameters for the separate parameters, as an alternative.

----

That said, if your project is strongly committed to using `double` only with your Au wrapper aliases: I was going to say it would be straightforward, but instead I think it will be tricky.

I was going to suggest writing your own `QuantityMaker` template, which uses `au::QuantityMaker` internally.  Then you'd define all your aliases in terms of it.

If all you wanted the custom maker to do was _create_ the quantities in a `double`-forcing way, then great!  This would be easy.  But `QuantityMaker` defines a bunch of other operators that I had forgotten about, and they're really important: they're what makes Au's composability possible.  You can multiply and divide quantity makers with each other, with magnitudes, etc.  So we really don't want to give that up.

I thought about adding an optional second template parameter for a forcing rep, but quickly realized that would be way too invasive of a change.

Hmm... :thinking:

**Comment by chiphogg** [comment]
Actually, I wonder if it would work if you just defined `operator*` and `operator/` with generic template arguments, using SFINAE (via trailing return types) to constrain it appropriately?

Something like the following (untested!!) should communicate what I had in mind.

```cpp
template <typename U>
struct QuantityMaker {
    template <typename R>
    constexpr ::au::QuantityD<U> operator(R x) const {
        return ::au::QuantityMaker<U>{}(static_cast<double>(x));
    }

    template <typename T>
    constexpr auto operator*(T x) const -> decltype(::au::QuantityMaker<U>{} * x) {
        return ::au::QuantityMaker<U>{} * x;
    }

    template <typename T>
    constexpr auto operator/(T x) const -> decltype(::au::QuantityMaker<U>{} / x) {
        return ::au::QuantityMaker<U>{} / x;
    }
};
```

The downside is that it would return Au's quantity makers, instead of your specialized ones.

**Comment by StefanoD** [comment]
> I'm guessing this is for cases where the compiler will fail to deduce T unless it deduces T to be the same type for every individual parameter?

Yes, but not only this. We are also using Qt and if you want to support custom types in Qt, you have to use a macro: `Q_DECLARE_METATYPE()`. We will be forced to do this for `double` an `int` Quantities.

And because we are having _many_ template code, all the changes would be pretty invasive.

I will try out your code snippet tomorrow, thanks! 😊

**Comment by chiphogg** [comment]
Perhaps this would be a little closer.  It's been very lightly tested, but should give enough of the idea.

```cpp

template <typename U>
struct QuantityMaker;

template <typename T>
struct ReplaceAuQuantityMakerWithOurQuantityMakerImpl {
    using type = T;
};
template <typename U>
struct ReplaceAuQuantityMakerWithOurQuantityMakerImpl<::au::QuantityMaker<U>> {
    using type = QuantityMaker<U>;
};
template <typename T>
using ReplaceAuQuantityMakerWithOurQuantityMaker =
    typename ReplaceAuQuantityMakerWithOurQuantityMakerImpl<T>::type;

template <typename U>
struct QuantityMaker {
    template <typename R>
    constexpr ::au::QuantityD<U> operator()(R x) const {
        return ::au::QuantityMaker<U>{}(static_cast<double>(x));
    }

    template <typename U2>
    constexpr auto operator*(QuantityMaker<U2>) const -> QuantityMaker<::au::UnitProductT<U, U2>> {
        return {};
    }

    template <typename U2>
    constexpr auto operator/(QuantityMaker<U2>) const -> QuantityMaker<::au::UnitQuotientT<U, U2>> {
        return {};
    }

    template <typename T>
    constexpr auto operator*(T x) const
        -> ReplaceAuQuantityMakerWithOurQuantityMaker<decltype(::au::QuantityMaker<U>{} * x)> {
        return {};
    }

    template <typename T>
    constexpr auto operator/(T x) const
        -> ReplaceAuQuantityMakerWithOurQuantityMaker<decltype(::au::QuantityMaker<U>{} / x)> {
        return {};
    }
};
```

The main change here is we say "multiply by any type that `QuantityMaker` can, but _if the result is an `au::QuantityMaker`_, then turn it into our kind of `QuantityMaker` instead".  (I also had to handle the case of two our-type-of-`QuantityMaker`-instances being multiplied or divided.)

I **think** this would work, and would do what you wanted as far as adapting quantity makers, without losing composability.  But I'd definitely recommend adding a bunch of unit tests to this utility if you end up deciding to go this route, as it's in somewhat uncharted waters.

**Comment by StefanoD** [comment]
Sadly, this doesn't work. It would be great to have a long-term solution and not a customized solution.

```cpp
using Meters = au::QuantityD<au::Meters>;
constexpr auto meters = QuantityMaker<au::Meters>{};

Meters m1 = meters(1);

bool isSame = m1.in(meters) == 1;
```

Results in the error:
```
<source>:78:24: error: no matching function for call to 'au::Quantity<au::Meters, double>::in(const QuantityMaker<au::Meters>&)'
   78 |     bool isSame = m1.in(meters) == 1;
      |                   ~~~~~^~~~~~~~
In file included from <source>:5:
/app/aurora-opensource.github.io/au/main/au_all_units.hh:3774:22: note: candidate: 'template<class NewRep, class NewUnit, class> constexpr NewRep au::Quantity<U, R>::in(NewUnit) const [with NewUnit = NewRep; <template-parameter-2-3> = NewUnit; UnitT = au::Meters; RepT = double]'
 3774 |     constexpr NewRep in(NewUnit u) const {
      |                      ^~
/app/aurora-opensource.github.io/au/main/au_all_units.hh:3774:22: note:   template argument deduction/substitution failed:
<source>:78:24: note:   couldn't deduce template parameter 'NewRep'
   78 |     bool isSame = m1.in(meters) == 1;
      |                   ~~~~~^~~~~~~~
/app/aurora-opensource.github.io/au/main/au_all_units.hh:3784:19: note: candidate: 'template<class NewUnit, class> constexpr au::Quantity<U, R>::Rep au::Quantity<U, R>::in(NewUnit) const [with <template-parameter-2-2> = NewUnit; UnitT = au::Meters; RepT = double]'
 3784 |     constexpr Rep in(NewUnit u) const {
```

See [compiler explorer](https://godbolt.org/z/cMs3orore)

**Comment by chiphogg** [comment]
Oh, of course --- I forgot about [unit slots](https://aurora-opensource.github.io/au/main/discussion/idioms/unit-slots/)!  The solution should have covered all of the _quantity making_ and _composing_ functions, but it doesn't handle the _unit slot_ functions.

Fortunately, this is pretty easy.  To make something compatible with unit slot APIs, you just need to define the [`AssociatedUnit` trait](https://aurora-opensource.github.io/au/main/reference/unit/#associated-unit) for it.  In this particular case, what you'd need is something like this in the top-level namespace:

```cpp
namespace au {
template <typename U>
struct AssociatedUnit<::QuantityMaker<U>> : stdx::type_identity<U> {};
} // namespace au
```

Looks like it works on [godbolt](https://godbolt.org/z/67eMYYqWb)!

**Comment by StefanoD** [comment]
Thanks, but it still has [problems](https://godbolt.org/z/zKssWEE4M):

```cpp
using Meters = au::QuantityD<au::Meters>;
using Millimeters = au::QuantityD<au::Milli<au::Meters>>;

constexpr auto meters = QuantityMaker<au::Meters>{};
constexpr auto millimeters = au::milli(meters);

Millimeters mm2 = millimeters(1);
bool isSame2 = mm2.in(millimeters) == 1;
```

```
<source>: In function 'int main(int, char**)':
<source>:88:26: error: no matching function for call to 'au::Quantity<au::Milli<au::Meters>, double>::in(const au::Milli<QuantityMaker<au::Meters> >&)'
   88 |     bool isSame2 = mm2.in(millimeters) == 1;
      |                    ~~~~~~^~~~~~~~~~~~~
In file included from <source>:5:
/app/aurora-opensource.github.io/au/main/au_all_units.hh:3774:22: note: candidate: 'template<class NewRep, class NewUnit, class> constexpr NewRep au::Quantity<U, R>::in(NewUnit) const [with NewUnit = NewRep; <template-parameter-2-3> = NewUnit; UnitT = au::Milli<au::Meters>; RepT = double]'
 3774 |     constexpr NewRep in(NewUnit u) const {
      |                      ^~
/app/aurora-opensource.github.io/au/main/au_all_units.hh:3774:22: note:   template argument deduction/substitution failed:
<source>:88:26: note:   couldn't deduce template parameter 'NewRep'
   88 |     bool isSame2 = mm2.in(millimeters) == 1;
      |                    ~~~~~~^~~~~~~~~~~~~
/app/aurora-opensource.github.io/au/main/au_all_units.hh:3784:19: note: candidate: 'template<class NewUnit, class> constexpr au::Quantity<U, R>::Rep au::Quantity<U, R>::in(NewUnit) const [with <template-parameter-2-2> = NewUnit; UnitT = au::Milli<au::Meters>; RepT = double]'
 3784 |     constexpr Rep in(NewUnit u) const {
      |                   ^~
```

I don't have a good feeling about this and not integrate this until their might be a solution within Au.

**Comment by chiphogg** [comment]
I haven't forgotten about this issue.  :slightly_smiling_face:  I've been turning it over in my head since your last update.

One of the key challenges is that, philosophically, Au tries very hard to minimize the changes to the program in going from "no units library" to "units library".  That means that something like `meters(...)` should just take _anything_, and return the quantity-of-meters version of it.  If you want an option where `meters(...)` _changes the backing type_, that's kind of an impedance mismatch with this philosophy.

As I see it, there are three categories of solution.

1. Train people to include the `.` in their literals, always.
2. Build a shim layer that sits on top of Au (basically, what we have in the latest godbolt link, plus some solution for prefixes).
3. Add a first-class library feature to Au (or at least, perhaps, an "advanced-usage and un-publicized" feature).

-----

The first option has its merits.  (Well, easy for me to say!)  It seems reasonable for people writing code to understand that there are integer types, and floating point types, and that they have different tradeoffs --- it kind of goes with the territory.  I could see this being socialized relatively easily, and people learning that "oh, this means you need to write it like `5.0` instead of `5`".

But I could well imagine that this creates too much friction for less technical users, and I definitely understand the value in minimizing friction.  Being fanatical about minimizing friction for our own use cases was critically important to me when I was writing Au!

-----

The second option seems very appealing to me.  I know it might feel like a dead end, as we have been hitting problems at every step so far, but I actually think we're very close!  The prefix appliers were [way less work than I expected](https://godbolt.org/z/WsGWcbW45) to solve.  True, you'd need to define `milli` instead of using `au::milli`, and so on for every prefix you want to provide, but at least it's reasonably straightforward.

So at this point, we'd have rep-forcing quantity makers that support composition (including with "vanilla" quantity makers), all unit slot APIs, and prefixes.  I'm not sure what (if anything) is left out, but that's certainly the vast bulk of the needed functionality.  I think if you stuck these abstractions in a single-file library within your project, and put up unit tests for the edge cases you can think of (adding more as you think of more), then that would be pretty solid overall.

-----

As for the third option, while it's my least preferred, I also haven't ruled it out.  I don't think I would document it if we added it, as it's at odds with the library's philosophy, but I could see a case for adding it in an `au::experimental` namespace.

I think the major downside here would be that it puts me in the critical path, which adds time and uncertainty.  I'd need to figure out how to structure it within the library, answer questions about single-file inclusion, etc.  The other two options are completely within your control.

-----

Anyway, there you have it.  Please let me know how well each option meets your needs, or if I've missed anything in my analysis!  I'm glad the library has been a promising fit for you so far, and I'm looking forward to figuring out the best way to get past this hurdle.

**Comment by StefanoD** [comment]
Hi and thanks for your answer!
Currently, I'm trying option one: Documenting that quantity makers should be usually called with a double literal. If the mid-term and long-term feedback is negative, I will try option 2.

Thanks again for your support! ☺️

**Comment by chiphogg** [comment]
Wonderful, glad I could help!

I'm going to close this issue before our team meeting today because I think it's resolved, but feel free to reopen and/or comment further if you need anything else.
