### ISSUE TITLE
Equality operator is very strict

### ISSUE THREAD

**Issue by StefanoD** [aurora-opensource/au#245]
Hi,
I am currently porting nholthaus units to Au units and one unit test is failing. The reason is that an serialization test which serializes, deserializes and compares the values, is very strict in Au.
The value of a unit before serialization is `1401.2250000000001`. After serialization and deserialization the value is `1401.2249999999999` which let the test fail.
I looked into nholthaus units which implemented the comparison operator like this:

```cpp
template<class ConversionFactorRhs, typename Ty, class NsRhs>
constexpr std::enable_if_t<std::is_floating_point_v<T> || std::is_floating_point_v<Ty>, bool> operator==(
    const unit<ConversionFactorRhs, Ty, NsRhs>& rhs) const noexcept
{
    using CommonUnit       = std::common_type_t<unit, unit<ConversionFactorRhs, Ty, NsRhs>>;
    using CommonUnderlying = typename CommonUnit::underlying_type;

    const auto common_lhs(CommonUnit(*this).linearized_value);
    const auto common_rhs(CommonUnit(rhs).linearized_value);

    return abs(common_lhs - common_rhs) <
        std::numeric_limits<CommonUnderlying>::epsilon() * abs(common_lhs + common_rhs) ||
        abs(common_lhs - common_rhs) < std::numeric_limits<CommonUnderlying>::min();
}
```

Does it makes sense to have something like this in Au?

The drawback would be propably a performance impact in runtime and compile time.

**Comment by StefanoD** [comment]
Maybe a `isAlmostEqual()` function would be more appropiate.

**Comment by chiphogg** [comment]
I've run into the same issue when porting nholthaus code, and, subsequently, spent a bunch of time thinking about it.  :slightly_smiling_face: 

We'll never make `operator==` less strict, because then `==` would no longer create equivalence classes; it breaks transitivity.  See my detailed discussion in [this comment](https://github.com/nholthaus/units/issues/118#issuecomment-1162240523).

As for the serialization/deserialization round trip changing the value: yep, I've run into this one a bunch too!  Both with Au types, and with other types (for example, I've seen code that uses different encodings of rotations in the C++ types, and "on the wire").  My thoughts on this:

1. Prefer serialization approaches that simply write out exactly the bits you have, no computation.  (For quantities, this means storing your value in the same units "on the wire" as in the C++ types.)
2. If we depart from this, then we're using lossy serialization, and therefore we can't guarantee exact equality when we deserialize.

**Comment by StefanoD** [comment]
Thank you, for your answer1
