### ISSUE TITLE
MSVC19 - Spaceship Operator triggers "C2338	static_assert failed: 'NTTP functionality only works when rep is built-in integral type'

### ISSUE THREAD

**Issue by MatthiasJeuthe** [aurora-opensource/au#353]
Hello Chip,

I noticed, that as soon as I export a class using the spaceship operator, I receive the error as mentioned in the title.
Minimal example: 

```
#define DLL_API __declspec(dllexport)

	struct DLL_API TestClass
	{
		auto operator<=>(const TestClass&) const = default;

		au::Quantity<au::Meters, double> thickness;
	};
```

It would be great, if you could take a look at it.

**Comment by chiphogg** [comment]
Thanks for raising this.  Very timely, as we are on the verge of cutting the next release!

I was extremely confused, but I finally figured out what is happening.  It turns out that `operator<=>` can't be automatically defined for `Quantity`, because its data member is `private`.  Normally, we would have defined it ourselves as a hidden friend, but we maintain C++14 compatibility, and we literally can't express `operator<=>` in C++14.  However, `Quantity` can now be _implicitly converted_ to the enum class `Quantity::NTTP`, which presumably _does_ support `<=>`.  Of course, since `Quantity<Meters, double>` is of floating point type, we (correctly and safely) produce a hard compiler error when we trigger this conversion.

You can immediately unblock yourself by adding this function somewhere after you include `"au/quantity.hh"` (directly, or indirectly via `"au/au.hh"`), and before you define `TestClass`:

```cpp
template <typename U1, typename R1, typename U2, typename R2>
constexpr auto operator<=>(const Quantity<U1, R1> &lhs, const Quantity<U2, R2> &rhs) {
    using U = CommonUnitT<U1, U2>;
    return lhs.in(U{}) <=> rhs.in(U{});
}
```

On the Au side, I think we can make a kind of `"au/au_cpp20.hh"` file, with appropriate CI testing.  Users on newer standards can include it to get library-supported fixes to handle features in newer standards.  Users on older standards won't be affected at all.

**Comment by chiphogg** [comment]
A colleague, @andrey-petr, pointed out that you could also change your return type from `auto` to `std::strong_ordering` in this case.  That would have the benefit of being a very simple change.  However, I think that `auto` better expresses author intent in this case, and probably would also scale better to structs with multiple members.

**Comment by MatthiasJeuthe** [comment]
Thank you for your quick response! The workaround you suggested works perfectly. 
Rather than placing the responsibility on the client to select the appropriate include, how about using a conditional approach like this?

```
#if __cplusplus >= 202002L
    // Code for C++20 or newer
#else
    // Code for older standards
#endif
```

Of course, this approach must be validated for the supported compilers.

**Comment by MatthiasJeuthe** [comment]
> A colleague, @andrey-petr, pointed out that you could also change your return type from `auto` to `std::strong_ordering` in this case. That would have the benefit of being a very simple change. However, I think that `auto` better expresses author intent in this case, and probably would also scale better to structs with multiple members.

I would rather not have a library in my code base which forces me to make changes...

**Comment by chiphogg** [comment]
> Thank you for your quick response! The workaround you suggested works perfectly. Rather than placing the responsibility on the client to select the appropriate include, how about using a conditional approach like this?
> 
> ```
> #if __cplusplus >= 202002L
>     // Code for C++20 or newer
> #else
>     // Code for older standards
> #endif
> ```
> 
> Of course, this approach must be validated for the supported compilers.

This would be quite a watershed moment for Au: I have always striven to avoid all macros in the library.  The bar for going from 0 to 1 macros would be very high.  However, I can't deny your compelling point, that it would be better if the library would simply continue to work out of the box.

We have always said we implicitly support not just C++14, but C++17, C++20, and all newer versions.  We've founded this claim mainly on backwards compatibility.  Here's a concrete example where that's not enough.  If we really support C++20, then we'll need to support straightforward use cases such as the one in your initial post.

I think I probably need to get over myself and give up on absolute purity on macros, when the technical tradeoffs are heavily lopsided.  :sweat_smile:  I still want to keep the bar very high, and not open the floodgates to a codebase littered with test macros. 
 However, this particular instance does seem like it meets that bar.

**Comment by MatthiasJeuthe** [comment]
I’m not particularly fond of macros either, but I believe prioritizing client convenience is more important in this case. At the moment, I can't think of a better alternative, so this approach seems like the most practical solution for now.

**Comment by chiphogg** [comment]
@MatthiasJeuthe, does #354 remove the need for you to add the manual implementation of `operator<=>(Quantity, Quantity)`?
